CREATE TABLE pedidos (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    usuario_id INTEGER NOT NULL,
    producto_id INTEGER NOT NULL,
    cantidad INTEGER NOT NULL,
    fecha TIMESTAMP NOT NULL,
    -- 👇 AGREGAMOS 'ENTREGADO' EN EL CHECK
    estado TEXT NOT NULL CHECK (estado IN ('PENDIENTE', 'PAGADO', 'ENTREGADO', 'CANCELADO')),
    monto REAL NOT NULL 
);